apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fc-hrsc-codeflix
  region: us-east-2
  version: "1.33"

iam:
  withOIDC: true

managedNodeGroups:
  - name: fc-hrsc-mng-db
    instanceType: t3.small
    desiredCapacity: 1
    labels:
      role: db
    iam:
      withAddonPolicies:
        ebs: true
  - name: fc-hrsc-mng-messaging
    instanceType: t3.small
    desiredCapacity: 1
    labels:
      role: messaging
    iam:
      withAddonPolicies:
        ebs: true

fargateProfiles:
  - name: fc-hrsc-fp-default
    selectors:
      - namespace: default
      - namespace: kube-system
  - name: fc-hrsc-fp-codeflix
    selectors:
      - namespace: codeflix
        labels:
          role: app

addons:
  - name: aws-ebs-csi-driver
    version: latest
