apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch

metadata:
  name: fc-hrsc-elasticsearch
  namespace: codeflix

spec:
  version: 8.15.1
  nodeSets:
    - name: default
      count: 1
      podTemplate:
        spec:
          nodeSelector:
            type: ec2
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: 0.8
                  memory: 1Gi
                limits:
                  cpu: 0.8
                  memory: 1Gi
      config:
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: fc-hrsc-elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: fc-hrsc-storageclass
