apiVersion: v1
kind: Service

metadata:
  name: fc-hrsc-nginx-service
  namespace: codeflix

spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - name: fc-hrsc-nginx-service
      protocol: TCP
      port: 80
      targetPort: 80
