apiVersion: v1
kind: Service

metadata:
  name: nginx-service
  namespace: codeflix

spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - name: nginx-service
      protocol: TCP
      port: 80
      targetPort: 80
