apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  name: fc-hrsc-storageclass

allowVolumeExpansion: true

provisioner: ebs.csi.aws.com

volumeBindingMode: WaitForFirstConsumer

reclaimPolicy: Delete

parameters:
  type: gp3
